apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-rwo
  namespace: openshift-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ocs-storagecluster-ceph-rbd
